### PR TITLE
feat: bump sparqlee version

### PR DESCRIPTION
**Pull request by jitsedesmet**
Bump sparqlee version and add spec tests for sparql 1.2 date support. Depends on: https://github.com/rubensworks/rdf-test-suite.js/pull/91

### CODE REVIEW

**Comment by jitsedesmet** [comment]
I'm having a though time with `yarn install` here. Whenever I call it, the preinstall script starts removing dependencies. However, these dependencies are needed.

**Comment by rubensworks** [comment]
> I'm having a though time with yarn install here. Whenever I call it, the preinstall script starts removing dependencies. However, these dependencies are needed.

Prob because you're using Node 18. Can you try with Node 16?

**Comment by jitsedesmet** [comment]
Ah yes, this seemed to be the issue, thank you!

**Comment by rubensworks** [comment]
A new rdf-test-suite version has been released, so bumping this here should fix the CI I guess.

**Comment by rubensworks** [comment]
Nice! Thanks @jitsedesmet.

**Pull request merged**
