### PR TITLE
Chore: merge expression bussification with V3

### PR DESCRIPTION
**Pull request by jitsedesmet**

### CODE REVIEW

**Comment by rubensworks** [comment]
@jitsedesmet Could you squash your last own commits into a single one?
Usually I would do this myself from the GH website here when merging, but I can't do this since there are other commits in this branch that we want to keep as-is.

See https://comunica.dev/contribute/#fix-bugs-or-implement-new-features for guidelines on the commit message format.

**Comment by rubensworks** [comment]
(If it's your first time squashing, I recommend making a backup of this branch first)

**Comment by jitsedesmet** [comment]
Interesting...  
image
That did not work...

**Comment by rubensworks** [comment]
Oops, I squashed the commits. I'll revert the squashed commit. Could you re-open the PR?

**Pull request merged**
