### PR TITLE
Merge busification branch with next/major

### PR DESCRIPTION
**Pull request by jitsedesmet**

### CODE REVIEW

**Comment by jitsedesmet** [comment]
Hey, not only compile, but only 1 spec test fails and integrations tests pass :D not bad already

**Comment by rubensworks** [comment]
No idea at first glance.

**Comment by jitsedesmet** [comment]
Had to restart because my fork was not up to date, but hey, we're up and running again (well, not running yet, but you get it)

**Comment by jitsedesmet** [comment]
Jippie , seems like this time around, spec and integration just passes

**Pull request merged**
