### PR TITLE
remove localizeBlankNodes from context

### PR DESCRIPTION
**Pull request by jitsedesmet**
This PR aims to resolve https://github.com/comunica/comunica/issues/1190

### CODE REVIEW

**Comment by jitsedesmet** [comment]
Seems like this already has the expected result:
```
./comunica-sparql-file "blank.ttl" -q "CONSTRUCT WHERE { ?s ?p ?o }"
_:bc_0_b0_bob a <http://xmlns.com/foaf/0.1/Person>;
    <http://xmlns.com/foaf/0.1/knows> <http://example.org/alice#me>;
    <http://schema.org/birthDate> "1990-07-04"^^<http://www.w3.org/2001/XMLSchema#date>;
    <http://xmlns.com/foaf/0.1/topic_interest> <http://www.wikidata.org/entity/Q12418>.
```

Now let's check the tests...

**Review by rubensworks — APPROVED** [review]
Yay, great work @jitsedesmet!

**Comment by rubensworks** [comment]
I see there's a CI failure due to an extra dependency that should be removed:

>  Task "depcheckTask" failed. Error: Extra dependencies: @comunica/context-entries in @comunica/actor-query-operation-construct

Could you look into removing it @jitsedesmet?

**Review by rubensworks — APPROVED** [review]
Excellent work! 🚀

**Pull request merged**
