### PR TITLE
BREAKING CHANGE: remove cross fetch

### PR DESCRIPTION
**Pull request by jeswr**

### CODE REVIEW

**Comment by surilindur** [comment]
I do not know if this removal is related, but `cross-fetch` has been removed in `next/major` (due to being a breaking change), or at least it was removed, in case it has been reverted since (#1330). Just dropping this comment here since I noticed the PR.

**Comment by rubensworks** [comment]
Indeed, this is already included in `next/major`.

@jeswr is this a strong requirement for the ESM stuff? If so, then it might be better to rebase your work onto `next/major`. (in that case, we may first want to merge `master` to it again)

@surilindur Can you double-check that all of the changes in this PR are also in `next/major` already?
If so, we can close this PR.

**Comment by surilindur** [comment]
I went through all the changes and they all seem to have been in that other PR already. The wording of the readme in actor-http-fetch is different between the two, however, so I think that should be checked. The version from here seems to be better.

**Comment by rubensworks** [comment]
Ok, thanks for checking @surilindur!

**Pull request closed without merging**
