### PR TITLE
Add support for SPARQL update

### LINKED ISSUE #435: SPARQL Update
#### Issue type:

- :heavy_plus_sign: Feature request

____
#### Description:

At the moment, we only support read-only queries.
In the future, we should also add support for [update queries](https://www.w3.org/TR/sparql11-update/).

### PR DESCRIPTION
**Pull request by rubensworks**
This PR adds the relevant buses and actors to fully implement the SPARQL 1.1 update spec,
and passes all spec tests.

At the moment, only in-memory updates are supported (to RDF/JS stores).
Other types (LDP, SPARQL GSP, local file, ...) can easily be added in the future by hooking on to the `rdf-update-quads` bus.

The only blocker to this is https://github.com/RubenVerborgh/AsyncIterator/pull/27, so once that one is merged, I'll also update and merge this PR here.

Closes #435
Related to #721

### CODE REVIEW

**Comment by jeswr** [comment]
> Other types (LDP, SPARQL GSP, local file, ...) can easily be added in the future by hooking on to the rdf-update-quads bus.

@rubensworks are you working on this, if not I can create a PR with local file and SPARQL actors soonish

**Comment by rubensworks** [comment]
@jeswr PRs for this are definitely welcome!

I do however first want to look into setting up a base architecture to enable hypermedia-driven update destinations (similar to `bus-rdf-resolve-hypermedia`). This should then allow Comunica to automatically detect the type of destination (LDP, SPARQL GSP, ...). I intend to start looking into that this week.

The local file actor would probably not be part of the hypermedia-based stack, so that might be something that's PR-able already.

**Comment by rubensworks** [comment]
Actually, you may want to wait with the file-based actor for a bit as well. My current hypermedia architecture can cope with (and simplify) that as well.

**Comment by sroze** [comment]
Great work 👏

**Comment by rubensworks** [comment]
@jeswr Just checking if you already had anything in the works for local file and/or SPARQL endpoint support?
If not, I'll probably look into implementing those in the near future.
But I can wait if you still want to look into this :-)

**Comment by jeswr** [comment]
> Just checking if you already had anything in the works for local file and/or SPARQL endpoint support?

No; got a few too many other commitments atm unfortunately. It's possible that the file update & write actors [here](https://github.com/jeswr/comunica/tree/hacky-finish/packages) or [here](https://github.com/jeswr/comunica/tree/feature/update-j/) could be cherry picked - but given that they were (very) rushed and built for different bus API's I'd say its unlikely.

**Comment by rubensworks** [comment]
@jeswr No worries. I'll have a look at them soon!

**Pull request merged**
