### PR TITLE
Update the jbr version used in WatDiv performance test

### PR DESCRIPTION
**Pull request by surilindur**
The changes here bump jbr version to the latest and update the experiment configurations accordingly for the WatDiv performance test.

### CODE REVIEW

**Comment by surilindur** [comment]
I have no idea why that fails in the CI, it works locally... will try to figure it out. :expressionless:

**Comment by rubensworks** [comment]
I just pushed a new commit to master that should fix the performance job in PRs.
So this should be fixed after rebasing.

**Comment by surilindur** [comment]
Awesome, thank you! The fixed sparql-benchmark-runner.js library should also fix the loading of queries, so I will restore the Node version used in here to 18.

**Comment by surilindur** [comment]
> so I will restore the Node version used in here to 18.

I did this, I forgot to mention it, I just removed the commit that bumped it to 20. Now, with the updated benchmark runner and after rebasing, the tests pass. :slightly_smiling_face: This should be ready now.

**Pull request merged**
