### PR TITLE
Fix Headers not being sent

### PR DESCRIPTION
**Pull request by ludwigschubi**
Related issue: https://github.com/comunica/comunica-feature-solid/issues/30

I used https://github.com/remodietlicher/comunica-solid-react-test to test the fix. 
To replicate the fix clone the repo, and use `yarn link` in the `packages/actor-http-fetch` directory on this branch to test the fixed version

Also added a small refactor that i saw, the tests were unaffected by it so i assume its good but let me know if its not then ill remove it :v:

### CODE REVIEW

**Comment by rubensworks** [comment]
Super, great work, thanks @ludwigschubi!

Released this in 2.4.3.
@remodietlicher Could you test this again on your end as well?

@ludwigschubi Once @remodietlicher has confirmed it's working on his end, we can look into finalizing the bounty.

**Comment by remodietlicher** [comment]
Hi Guys! Thanks a lot for your fix. I'm currently testing it with some success, but not all my cases that work with https://rdf.js.org/N3.js/docs/N3Store.html seem to work with solid pods. I'll have to dig a bit deeper to make sure I'm not just doing something wrong and will get to you as soon as I know more.

**Comment by remodietlicher** [comment]
After a little detour I can confirm that what I wanted to do works!

**Comment by rubensworks** [comment]
Excellent, thanks for checking @remodietlicher!

@ludwigschubi feel free to send an invoice to https://opencollective.com/comunica-association with the agreed bounty amount to finalize the bounty. Thanks again for the great work!

**Pull request merged**
