### PR TITLE
fix: don't lookup default graph when none available

### PR DESCRIPTION
**Pull request by jeswr**
From [QPF 3.4](https://linkeddatafragments.org/specification/quad-pattern-fragments/#:~:text=if%20this%20default%20graph%20contains%20at%20least%20one%20triple): "Each [...] Fragment and [...] page MUST contain a triple [...] declaring the default graph [...] if this [...] contains at least one triple."

This means that if we know we are looking at a QPF endpoint and the `sd:defaultGraph` is not defined, then we can just return an empty stream when data from the default graph is requested. @rubensworks do you agree with this interpretation, if so I will forge ahead with this PR.

### CODE REVIEW

**Comment by jeswr** [comment]
Marking as draft as this is still resulting in some unecessary pagination

before:
```
SELECT * WHERE { ?s ?p ?o }
requesting https://fragments.ap.inrupt.com/qpf?storage=https%3A%2F%2Fstorage.ap.inrupt.com%2F311cdda9-cb55-465b-861d-5b1e4dc6ea38%2F
creating https://fragments.ap.inrupt.com/qpf?storage=https%3A%2F%2Fstorage.ap.inrupt.com%2F311cdda9-cb55-465b-861d-5b1e4dc6ea38%2F&graph=
requesting https://fragments.ap.inrupt.com/qpf?storage=https%3A%2F%2Fstorage.ap.inrupt.com%2F311cdda9-cb55-465b-861d-5b1e4dc6ea38%2F&graph=
[]
```
after:
```
SELECT * WHERE { ?s ?p ?o }
requesting https://fragments.ap.inrupt.com/qpf?storage=https%3A%2F%2Fstorage.ap.inrupt.com%2F311cdda9-cb55-465b-861d-5b1e4dc6ea38%2F
requesting https://fragments.ap.inrupt.com/qpf?storage=https%3A%2F%2Fstorage.ap.inrupt.com%2F311cdda9-cb55-465b-861d-5b1e4dc6ea38%2F&after=170095
[]
```

**Comment by rubensworks** [comment]
I even forgot about that line in the spec. But yes, it sounds like a correct interpretation to me!

**Comment by jeswr** [comment]
@rubensworks It might be good to have a bounty for integration tests against a mocked TPF and QPF endpoint testing for characteristics such as:

 - The engine only collects the necessary pages (doesn't try and get default graphs if there are none, doesn't paginate too far, etc.)
  - The engine collects the correct data (doesn't put triples from a QPF endpoint without a default graph into the default graph)
  -

**Comment by jeswr** [comment]
Flakey browser test at it again: https://github.com/comunica/comunica/actions/runs/4120590815

**Comment by rubensworks** [comment]
Super, thanks @jeswr!

> @rubensworks It might be good to have a bounty for integration tests against a mocked TPF and QPF endpoint testing for characteristics such as:

Sure, good idea. Feel free to write this up in an issue at https://github.com/comunica/manifest-ldf-tests. Perhaps Inrupt may be open to funding this bounty?

**Pull request merged**
