### PR TITLE
Update jsonld-streaming-parser to latest version

### PR DESCRIPTION
**Pull request by brechtvdv**

### CODE REVIEW

**Comment by rubensworks** [comment]
Thanks!

**Comment by brechtvdv** [comment]
Can you update the actor description also to use the latest version? https://linkedsoftwaredependencies.org/bundles/npm/%40comunica%2Factor-rdf-parse-jsonld/1.21.1

**Comment by rubensworks** [comment]
Not sure what you mean.
That document is auto-generated based on the published npm package.

**Comment by brechtvdv** [comment]
Ah the link to jsonld-streaming-parser (/2.3.0) redirects to the latest version (2.3.1). So nevermind :)

**Pull request merged**
