### PR TITLE
perf: remove unecessary TransformIterator

### PR DESCRIPTION
**Pull request by jeswr**

### CODE REVIEW

**Comment by rubensworks** [comment]
I just pushed some changes to that file this morning, so it has some conflicts now...

But I think you're right in that this TransformIterator wrapper is not required anymore (it definitely used to be at some point).

However, are you sure that there's actually a performance benefit? Because the wrapper still avoids `getDuplicateElementLinks` being called in some cases (but its impact should be minor in any case).

**Comment by jeswr** [comment]
Would need to double check but I think the setup meant that all elements were being buffered through the transform iterator which can have non-negligible impacts depending on the source.

**Comment by rubensworks** [comment]
Any updates on this?
If not, feel free to close this PR.

**Comment by rubensworks** [comment]
Closing this due to staleness. Feel free to re-open again later.

**Pull request closed without merging**
